RH_CV/Controllers/ManageHVController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RH_CV.Data;
using RH_CV.Models;
using RH_CV.Services.Contract;
using RH_CV.Sources;
using Rotativa.AspNetCore;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Security.Claims;
using System.Web;

namespace RH_CV.Controllers
{
    //[Authorize(Policy = "RolPolicy")]
    [Authorize]
    public class ManageHVController : Controller
    {
        private readonly IUserService _userService;
        //private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _contexto;
        public ManageHVController(IUserService userService, ApplicationDbContext contexto/*, UserManager<IdentityUser> userManager*/)
        {
            _contexto = contexto;
            _userService = userService;
            //_userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> MyHV()
        {
            ClaimsPrincipal claimsUser = HttpContext.User;
            string idUser = "";

            //ViewData["RolTipo"] = rol.Tipo;
            //claimsUser.Claims.Where(c=> c.Type == ClaimTypes.)

            if (claimsUser.Identity.IsAuthenticated)
            {
                idUser = claimsUser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            //var hojasDeVida = await _contexto.DatosPersonales.Where(hv => hv.Id == id).ToListAsync();
            //return View(hojasDeVida);
            return View(await _contexto.DatosPersonales.Include(hv => hv.Usuario).Where(hv => hv.UsuarioId == idUser).ToListAsync());
        }

        //MostrarHV
        [HttpGet]
        public async Task<IActionResult> AllHV()
        {
            // Obtener el ID del usuario actualmente autenticado
            //string userId = User.Identity.GetUserId();
            string userRol = Utilities.GetRol(HttpContext, _contexto);
            if (userRol == "Admin" || userRol == "Observador")
            {
                return View(await _contexto.DatosPersonales.Include(x => x.Usuario).ToListAsync());
            }

            //ClaimsPrincipal claimsUser = HttpContext.User;
            //string userId = "";

            //if (claimsUser.Identity.IsAuthenticated)
            //{
            //    userId = claimsUser.Claims.Where(c => c.Type == ClaimTypes.Name)
            //            .Select(c => c.Value).SingleOrDefault();
            //    // Obtener el rol del usuario
            //    Rol rol = _contexto.Usuario.Where(u => u.User == userId).Select(u => u.Rol).FirstOrDefault();

            //    // Verificar si el usuario es un administrador
            //    if (rol != null && rol.Id == 1 || rol != null && rol.Id == 2)
            //    {
            //        return View(await _contexto.DatosPersonales.ToListAsync());
            //    }
            //    else
            //    {
            //        return RedirectToAction("AccessDenied", "Home");
            //    }
            //}
            else
            {
                return RedirectToAction("AccessDenied", "Home");
            }
        }

        //CrearHV
        public IActionResult CreateHV()
        {
            ClaimsPrincipal claimsUser = HttpContext.User;
            string idUser = "";
            string primerNombre = "";
            string segundoNombre = "";
            string primerApellido = "";
            string segundoApellido = "";

            //ViewData["RolTipo"] = rol.Tipo;
            //claimsUser.Claims.Where(c=> c.Type == ClaimTypes.)

            if (claimsUser.Identity.IsAuthenticated)
            {
                idUser = claimsUser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();

                ViewData["idUser"] = idUser;

                var usuario = _contexto.Usuario.Find(idUser);
                if (usuario == null)
                {
                    return NotFound();
                }

                primerNombre = usuario.PrimerNombre;
                ViewData["primerNombre"] = primerNombre;

                segundoNombre = usuario.SegundoNombre;
                if(segundoNombre == null)
                {
                    segundoNombre = "ㅤ";
                }
                ViewData["segundoNombre"] = segundoNombre;

                primerApellido = usuario.PrimerApellido;
                ViewData["primerApellido"] = primerApellido;

                segundoApellido = usuario.SegundoApellido;
                if(segundoApellido == null)
                {
                    segundoApellido = "ㅤ";
                }
                ViewData["segundoApellido"] = segundoApellido;

                var vinculo = _contexto.TipoVinculo.Find(usuario.TipoVinculoId);
                if (vinculo == null)
                {
                    vinculo.Tipo = "ㅤ";
                }
                ViewData["VinculoTipo"] = vinculo.Tipo;

                var contrato = _contexto.TipoContrato.Find(usuario.TipoContratoId);
                if (contrato == null)
                {
                    contrato = new TipoContrato { Tipo = "ㅤ" };
                    //contrato.Tipo = "ㅤ";
                }
                ViewData["ContratoTipo"] = contrato.Tipo;

                var infoDocumento = _contexto.InfoDocumento.Find(usuario.InfoDocumentoId);
                if (infoDocumento.PaisExpedicion == null)
                {
                    infoDocumento.PaisExpedicion = "ㅤ";
                }
                ViewData["PaisExpedicion"] = infoDocumento.PaisExpedicion;

                if (infoDocumento.MunicipioExpedicion == null)
                {
                    infoDocumento.MunicipioExpedicion = "ㅤ";
                }
                ViewData["MunicipioExpedicion"] = infoDocumento.MunicipioExpedicion;

                //var tipoDocumento = _contexto.InfoDocumento
                //    .Where(id => id.TipoDocumentoId == usuario.InfoDocumentoId)
                //    .Select(id => id.TipoDocumento)
                //    .FirstOrDefault();

                //var tipoDocumento = _contexto.TipoDocumento.SingleOrDefault(td => td.Id == infoDocumento.TipoDocumentoId);
                //infoDocumento = _contexto.InfoDocumento
                //    .Include(i => i.TipoDocumento)
                //    .FirstOrDefault(i => i.Id == usuario.InfoDocumentoId);

                //var tipoDocumento = infoDocumento.TipoDocumento?.Tipo;
                var tipoDocumento = _contexto.TipoDocumento.Find(infoDocumento.TipoDocumentoId);
                //            var tipoDocumento = _contexto.TipoDocumento
                //.Where(td => td.Id == infoDocumento.TipoDocumentoId)
                //.Select(td => td.Tipo)
                //.FirstOrDefault();
                if (tipoDocumento == null)
                {
                    tipoDocumento.Tipo = "ㅤ";
                }
                ViewData["DocumentoTipo"] = tipoDocumento.Tipo;
            }

            //var rol = _contexto.Rol.Find(idUser);
            //if (rol == null)
            //{
            //    return NotFound();
            //}

            //var claimsIdentity = (ClaimsIdentity)User.Identity;
            //var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //var user = _contexto.Usuario.Select(i => i.User);

            //var user = _userManager.GetUserAsync(User);
            //var UsuarioId = user.Id;

            object[] drop = Utilities.DropDownList(_contexto);

            //ViewBag.TipoVinculo = drop[0];
            //ViewBag.TipoContrato = drop[1];
            //ViewBag.TipoDocumento = drop[2];
            ViewBag.EPS = drop[3];
            ViewBag.FondoPensiones = drop[4];
            ViewBag.FondoCesantias = drop[5];

            var years = Enumerable.Range(DateTime.Now.Year, 1950);
            ViewBag.Years = new SelectList(years, "Año", "Año");

            //TipoDocumento
            //var documentos = _contexto.TipoDocumento.Select(d => new SelectListItem
            //{
            //    Value = d.Id.ToString(),
            //    Text = d.Tipo,
            //});
            //ViewBag.TipoDocumento = documentos;

            //TipoVinculo
            //var tiposVinculo = _contexto.TipoVinculo.ToList();
            //ViewBag.TiposVinculo = tiposVinculo;


            ////TipoDocumento
            //var documentos = _contexto.TipoDocumento.Select(d => new SelectListItem
            //{
            //    Value = d.Id.ToString(),
            //    Text = d.Tipo,
            //});
            //ViewBag.Documentos = documentos;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateHV(DatosPersonales modelo, List<DatosFamiliares>? datosFamiliares, List<InfoLaboral>? infoLaboral, List<Escolaridad> escolaridad, List<ContactoEmergencia> contactoEmergencia, List<ReferenciasFamiliares> referenciasFamiliares, List<ReferenciasPersonales> referenciasPersonales)
        {
            ClaimsPrincipal claimsUser = HttpContext.User;
            string idUser = "";

            if (claimsUser.Identity.IsAuthenticated)
            {
                idUser = claimsUser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["idUser"] = idUser;

            string userRol = Utilities.GetRol(HttpContext, _contexto);
            //var user = await _userManager.GetUserAsync(User);
            //var UsuarioId = user.Id;

            //var documentos = _contexto.TipoDocumento.Select(d => new SelectListItem
            //{
            //    Value = d.Id.ToString(),
            //    Text = d.Tipo,

RH_CV/Views/ManageHV/AllHV.cshtml
@model IEnumerable<RH_CV.Models.DatosPersonales>;

@{
    ViewData["Title"] = "Hojas De Vida";
}

<h1 class="text-center mb-2">Hojas de Vida</h1>

<div class="d-flex justify-content-between mb-3">
    <a href="@Url.Action("Index","Home")">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6.354 4.354a.5.5 0 0 1 0 .707L3.707 8H14.5a.5.5 0 0 1 0 1H3.707l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.707l3-3a.5.5 0 0 1 .708 0Z" />
        </svg> Regresar
    </a>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Empleados</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <div class="table-wrapper">
                        @if (Model.Count() > 0)
                        {
                            <table class="table table-bordered table-hover" id="tblDatosPersonales" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Documento</th>
                                        <th>Primer Nombre</th>
                                        <th>Primer Apellido</th>
                                        <th>@Html.DisplayNameFor(m => m.Email)</th>
                                        <th>@Html.DisplayNameFor(m => m.Celular)</th>
                                        <th>Fecha Nacimiento</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <th>@Html.DisplayFor(m => item.Usuario.User)</th>
                                            <th>@Html.DisplayFor(m => item.Usuario.PrimerNombre)</th>
                                            <th>@Html.DisplayFor(m => item.Usuario.PrimerApellido)</th>
                                            <th>@Html.DisplayFor(m => item.Email)</th>
                                            <th>@Html.DisplayFor(m => item.Celular)</th>
                                            <th>@item.FechaNacimiento.ToString("dd-MM-yyyy")</th>
                                            <td>
                                                <a asp-action="DetailHV" asp-route-id="@item.Id">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16" style="color: #00C1FF;">
                                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                                    </svg></a>
                                                @*&nbsp;&nbsp;
                                                <a asp-action="EditHV" asp-route-id="@item.Id">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16" style="color:#F7A100">
                                                    <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                                                    </svg></a>*@
                                                @*<a class="btn btn-danger" asp-action="DeleteHV" asp-route-Id="@item.Id."><i class="bi bi-eraser-fill"></i> Borrar</a>*@
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>No hay registros</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="d-flex justify-content-center">
        <a href="@Url.Action("GetHVExcelFile","ManageHV")">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text-fill" viewBox="0 0 16 16">
                <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM4.5 9a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 1 0-1h4a.5.5 0 0 1 0 1h-4z" />
            </svg>      Descargar HV
        </a>
        <div class="mb-3">ㅤㅤㅤ</div>
        <a href="@Url.Action("GetActiveHVExcelFile","ManageHV")">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text-fill" viewBox="0 0 16 16">
                <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM4.5 9a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 1 0-1h4a.5.5 0 0 1 0 1h-4z" />
            </svg>      Descargar HV activos
        </a>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            //Llamar a datatable
            $('#tblDatosPersonales').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}

RH_CV/Views/ManageHV/DeleteHV.cshtml
@model RH_CV.Models.DatosPersonales

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "HV Detail";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Datos Personales</title>
    <link href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/smart_wizard.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/smart_wizard_theme_arrows.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="card ">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs pull-right" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#datosPersonales" role="tab" aria-controls="home" aria-selected="true">Hoja de vida laboral</a>
                </li>
                <!--<li class="nav-item">
                   <a class="nav-link" id="acerca-tab" data-toggle="tab" href="#acerca" role="tab"
                      aria-controls="acerca"
                      aria-selected="false">Público</a>
                   </li>

                   <li class="nav-item">
                   <a class="nav-link" id="conectividad-tab" data-toggle="tab" href="#conectividad" role="tab"
                      aria-controls="conectividad"
                      aria-selected="false">Ambiente Universitario </a>

                   </li>
                   <li class="nav-item">
                   <a class="nav-link" id="virtual-tab" data-toggle="tab" href="#virtual" role="tab"
                      aria-controls="virtual"
                      aria-selected="false">Costo de Vida</a>

                   </li>
                   <li class="nav-item">
                   <a class="nav-link" id="academica-tab" data-toggle="tab" href="#academica" role="tab"
                      aria-controls="academica"
                      aria-selected="false">Calidad de Educación Superior</a>
                   </li>-->
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="Personal" role="tabpanel" aria-labelledby="home-tab">

                    <form asp-action="DeleteHV">

                        <!--ID del usuario como campo oculto-->
                        <input type="hidden" asp-for="Id" />

                        <div id="divNombreDimension_1" class="col-md-12 alert alert-warning" role="alert" style="text-align:center;background-color:#DE3163;color: #FFFFFF;border-color:#d3255c">
                            <b>Hoja de Vida</b>
                        </div>
                        <div class="row align-items-baseline">
                            @*<div class="col-md-3" id="diva1">
                                <label>Tipo de Vinculo</label>
                                <label class="list-group-item" readonly>@Model.TipoVinculo</label>
                            </div>
                            <div class="col-md-3" id="diva1">
                                <label>Tipo de Contrato</label>
                                <label class="list-group-item" readonly>@Model.TipoContrato</label>
                            </div>
                            <div class="col-md-3" id="div1">
                                <label>Tipo de documento</label>
                                <select asp-for="TipoDocumentoId" asp-items="@ViewBag.Documentos" class="form-control"></select>
                                <label class="list-group-item" readonly>@Model.InfoDocumento.TipoDocumento</label>
                            </div>
                            <div class="col-md-3" id="div2">
                                <label>Número de documento</label>
                                <label class="list-group-item" readonly>@Model.Documento</label>
                            </div>*@
                        </div>
                        <br />
                        <div class="row align-items-baseline">
                            <div class="row align-items-baseline">
                                <label>Hijos</label>
                                <label readonly>@Model.PersonasACargo.Hijo</label>
                            </div>
                            <div class="row align-items-baseline">
                                <label>Conyugue</label>
                                <label readonly>@Model.PersonasACargo.Conyugue</label>
                            </div>
                            <div class="row align-items-baseline">
                                <label>Padres</label>
                                <label readonly>@Model.PersonasACargo.Padres</label>
                            </div>
                            <div class="row align-items-baseline">
                                <label>Otros</label>
                                <label readonly>@Model.PersonasACargo.Otros</label>
                            </div>
                        </div>
                        <hr>
                        <br>
                        <div class="form-row">
                            <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar al usuario?')">
                                Delete
                            </button>
                        </div>
                    </form>
                    <a asp-controller="ManageUsers" asp-action="AllUsers">Back</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

RH_CV/Views/ManageHV/MyHV.cshtml
@model IEnumerable<RH_CV.Models.DatosPersonales>;

@{
    ViewData["Title"] = "Hoja De Vida";
}

<h1 class="text-center">&nbsp;</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white text-center"><strong>Mi hoja de vida</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-bordered table-hover" id="tblDatosPersonales" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Documento</th>
                                    <th>Primer Nombre</th>
                                    <th>Primer Apellido</th>
                                    <th>Email</th>
                                    <th>Fecha Nacimiento</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>@Html.DisplayFor(m => item.Usuario.User)</th>
                                    <th>@Html.DisplayFor(m => item.Usuario.PrimerNombre)</th>
                                    <th>@Html.DisplayFor(m => item.Usuario.PrimerApellido)</th>
                                    <th>@Html.DisplayFor(m => item.Email)</th>
                                    <th>@item.FechaNacimiento.ToString("dd-MM-yyyy")</th>
                                    <td>
                                        <a asp-action="DetailHV" asp-route-id="@item.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16" style="color: #00C1FF;">
                                                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                                <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                                            </svg></a>
                                        &nbsp;&nbsp;
                                        <a asp-action="EditHV" asp-route-id="@item.Id">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16" style="color:#F7A100">
                                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                            </svg></a>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No hay ningún HV creado</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@if (Model.Count() == 0)
{
    <br />
    <div class="row">
        <div class="d-flex justify-content-center">
            <a href="@Url.Action("CreateHV","ManageHV")" class="btn d-block btn-lg gradient-custom-2 mb-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-plus-fill" viewBox="0 0 16 16">
                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0z" />
                </svg>      Crear Hoja de Vida
            </a>
        </div>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            //Llamar a datatable
            $('#tblDatosPersonales').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                            pagingType: "full_numbers_circle"
                }
            });
        });
    </script>
}